models/movie.py
from server import db


class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256), nullable=False)
    year = db.Column(db.DateTime, nullable=True)

    def __init__(self, title, year):
        self.title = title
        self.year = year

views/auth.py
from flask import Blueprint


# Defining a blueprint
auth = Blueprint('auth', __name__)

@auth.route('/admin')   # Focus here
def admin_home():
    return "Hello Admin!"

views/movies.py
from datetime import datetime
from flask import Blueprint, render_template, abort, redirect, url_for, request

# Defining a blueprint
movies = Blueprint('movies', __name__)

@movies.route('/')
def home_page():
    today = datetime.today()
    day_name = today.strftime("%A")
    return render_template("home.html", day=day_name)


@movies.route('/movies', methods=['GET', 'POST'])
def movies_page():
    from models.movie import Movie, db

    if request.method == "GET":
        movies = Movie.query.all()
        if movies is None:
            abort(404)
        return render_template("movies.html", movies=movies)
    else:
        form_movie_keys = request.form.getlist("movie_keys")
        for form_movie_key in form_movie_keys:
            movie_id = Movie.query.get(form_movie_key)
            db.session.delete(movie_id)
            db.session.commit()
        return redirect(url_for("movies_page"))

@movies.route('/movie/<int:movie_key>', methods=['GET', 'POST'])
def movie_page(movie_key):
    from models.movie import Movie

    movie = Movie.query.get(movie_key)
    if movie is None:
        abort(404)
    return render_template("movie.html", movie=movie)

@movies.route('/movie/add', methods=['GET', 'POST'])
def movie_add_page():
    from models.movie import Movie, db

    if request.method == "GET":
        return render_template(
            "movie_edit.html", min_year=1887, max_year=datetime.now().year)
    else:
        form_title = request.form["title"]
        form_year = request.form["year"]
        movie = db.session.add(Movie(form_title if form_title else "Nothing", datetime.datetime.now()))
        db.session.commit()
        return redirect(url_for("movie_page", movie_key=movie.key))

templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <section class="hero">
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">My movie collection</h1>
          <p class="subtitle">Have a nice {{ day }}!</p>
        </div>
      </div>
    </section>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> HELLO WORLD </h2>
</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>My movies - {% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"/>
    <link rel="stylesheet"
          href="{{ url_for('static', filename='mymovies.css') }}"/>
  </head>
  <body>
    <header>
      <nav class="navbar" aria-label="main navigation">
        <div class="navbar-brand">
          <span class="navbar-item">
            <a class="button is-link" href="{{ url_for('movies.home_page') }}">Home</a>
          </span>
          <span class="navbar-item">
            <a class="button is-link" href="{{ url_for('movies.movies_page') }}">List movies</a>
          </span>
            <span class="navbar-item">
            <a class="button is-link" href="{{ url_for('movies.movie_add_page') }}">Add movie</a>
          </span>
        </div>
      </nav>
    </header>

    <main>
      <section class="section">
        <div class="content">
          {% block content %}{% endblock %}
        </div>
      </section>
    </main>

    <footer class="footer">
      <div class="content">
        <small>&copy; 2023, Pavel Shepshelevich</small>
      </div>
    </footer>
  </body>
</html>

templates/movie.html
{% extends "layout.html" %}
{% block title %}Movie{% endblock %}
{% block content %}
    <h1 class="title">Movie</h1>

    <table class="table">
        <tr>
            <th>Title: </th>
            <td>
              {{ movie.title }}
            </td>
        </tr>
        <tr>
            <th>Year </th>
            <td>
              {% if movie.year %} {{ movie.year }} {% endif %}
            </td>
        </tr>
    </table>
{% endblock %}

templates/movie_edit.html
{% extends "layout.html" %}
{% block title %} Edit movie  {% endblock %}

{% block content %}
    <h1 class="title">Edit movie</h1>
     <form action="" method="post" name="movie_edit">
      <div class="field">
        <label for="title" class="label">Title</label>
        <div class="control">
          <input type="text" name="title" class="input" required="required"/>
        </div>
      </div>

      <div class="field">
        <label for="year" class="label">Year</label>
        <div class="control">
          <input type="number" name="year" class="input"
                 min="{{ min_year }}" max="{{ max_year }}"/>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <button class="button is-primary is-small">Save</button>
        </div>
      </div>
    </form>
{% endblock %}

templates/movies.html
{% extends "layout.html" %}
{% block title %}Movie list{% endblock %}
{% block content %}
    <h1 class="title">Movies</h1>

    {% if movies %}
    <form action="" method="post" name="movie_list">
      <table class="table is-striped is-fullwidth">
        {% for movie in movies %}
        <tr>
          <td>
            <label class="checkbox">
              <input type="checkbox" name="movie_keys" value="{{ movie.id }}"/>
            </label>
            <a href="{{ url_for('movies.movie_page', movie_key=movie.id) }}">
              {{ movie.title }}
              {% if movie.year %} ({{ movie.year }}) {% endif %}
            </a>
          </td>
        </tr>
        {% endfor %}
      </table>

      <div class="field is-grouped">
        <div class="control">
          <button class="button is-danger is-small">Delete</button>
        </div>
      </div>
    </form>
    {% endif %}
{% endblock %}